### ISSUE TITLE
Analytics Episode Details: Graphs not showing up

### ISSUE THREAD

**Issue by kl1lercher** [podlove/podlove-publisher#1407]
### Expected behavior

Episode Details in Analytics used to show bars and filtering was available by clicking on different properties

### Actual behavior

Analytics Episode Details not showing up after i've updated to 4.x. Analytics Overview, the startpage, is showing data.
To be fair, i recently reactivated analytics after it was disabled for years. 

![Episode Details not displaying charts](https://github.com/podlove/podlove-publisher/assets/3652205/92777a6c-c3e3-4a13-b8a4-662218a3f5a2)

![Analytics Overview is working as expected](https://github.com/podlove/podlove-publisher/assets/3652205/cc92879a-891b-4799-a7a0-0ac0aa35cceb)

### System information (see `Podlove > Support` menu)

Website                    https://techtelmechtel-podcast.at
PHP Version                8.1.25
WordPress Version          6.4.1
WordPress Theme            Twenty Nineteen v2.7
Active Plugins             
           - Antispam Bee v2.11.5
           - BackWPup v4.0.1
           - Classic Editor v1.6.3
           - Complianz | GDPR/CCPA Cookie Consent v6.5.5
           - Copy & Delete Posts v1.4.3
           - XML Sitemap Generator for Google v4.1.13
           - Plugin Compatibility Checker v2.5.8
           - Podlove Podcast Publisher v4.0.6
           - Podlove Subscribe Button v1.3.10
           - Podlove Web Player v5.7.1
           - Redirection v5.3.10
           - Statify v1.8.4
           - W3 Total Cache v2.6.0
           - Yoast SEO v21.5
           - Connect Matomo v1.0.30
           - WP YouTube Lyte v1.7.22
WordPress Database Charset utf8mb4
WordPress Database Collate 
Publisher Version          4.0.6
Publisher Database Version 153
Web Player Version         player_v5
open_basedir               ok
curl Version               7.74.0
iconv                      available
simplexml                  ok
max_execution_time         600
upload_max_filesize        100M
memory_limit               256M
disable_classes            
disable_functions          
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       https://techtelmechtel-podcast.at/feed/mp3/
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Thanks for the report! Fixed in next release.

**Comment by kl1lercher** [comment]
Hate to do this, but, update came in within minutes, but graphs are unfortunately still not showing up.
Console just showing a Server Error 500 for i guess  the necessary component

<img width="1620" alt="Screenshot 2023-11-21 at 08 49 17" src="https://github.com/podlove/podlove-publisher/assets/3652205/500b2b69-ebce-44b9-a2ac-b0ac75e54fc2">

**Comment by eteubert** [comment]
@kl1lercher can you check your PHP error log? The 500 response means the PHP script fails for some reason.

You may need to enable debug logging first, see https://wordpress.org/documentation/article/debugging-in-wordpress/

**Comment by kl1lercher** [comment]
here you go

`[21-Nov-2023 10:45:29 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /usr/www/users/creatijw/techtelmechtelfm/wp-includes/functions.php on line 7241
[21-Nov-2023 10:45:29 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /usr/www/users/creatijw/techtelmechtelfm/wp-includes/functions.php on line 2187
[21-Nov-2023 10:45:31 UTC] PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /usr/www/users/creatijw/techtelmechtelfm/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/ajax/ajax.php:229
Stack trace:
#0 [internal function]: Podlove\AJAX\Ajax->Podlove\AJAX\{closure}()
#1 /usr/www/users/creatijw/techtelmechtelfm/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/ajax/ajax.php(230): array_map()
#2 /usr/www/users/creatijw/techtelmechtelfm/wp-includes/class-wp-hook.php(324): Podlove\AJAX\Ajax->analytics_episode_average_downloads_per_hour()
#3 /usr/www/users/creatijw/techtelmechtelfm/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 /usr/www/users/creatijw/techtelmechtelfm/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /usr/www/users/creatijw/techtelmechtelfm/wp-admin/admin-ajax.php(188): do_action()
#6 {main}
  thrown in /usr/www/users/creatijw/techtelmechtelfm/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/ajax/ajax.php on line 229
`

**Comment by eteubert** [comment]
Well dividing by zero is tough 😬 

> PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in [...]/podlove-podcasting-plugin-for-wordpress/lib/ajax/ajax.php:229

Should be an easy fix, thanks for looking up the error!
